# Linear-time Temporal Logic (LTL)

## LTL Lexer

In [1]:
from ml2.ltl import lex_ltl

In [2]:
lex_ltl('a U X b')

['a', 'U', 'X', 'b']

## LTL Parser

In [3]:
from ml2.ltl import parse_ltl

In [4]:
parse_ltl('X a R b')

BinaryAST('R', [BinaryAST('X', [BinaryAST('a', [])]), BinaryAST('b', [])])

## LTL Formula

In [5]:
from ml2.ltl import LTLFormula

In [6]:
formula = LTLFormula.from_str('a U G b', 'infix')

In [7]:
formula.ast

BinaryAST('U', [BinaryAST('a', []), BinaryAST('G', [BinaryAST('b', [])])])

## LTL Spec

In [8]:
from ml2.ltl import LTLSpec

In [9]:
spec_dict = {
    "assumptions": [
      "G i0",
      "i0 & i1"
    ],
    "guarantees": [
        "G ! (o0 & o1)",
        "(G ((i0) -> (F (o0))))",
        "(G ((i1) -> (F (o1))))"
      ],
      "inputs": [
        "i0",
        "i1"
      ],
      "outputs": [
        "o0",
        "o1"
      ],
}

In [10]:
spec = LTLSpec.from_dict(spec_dict)

## LTL Spec Encoder

In [11]:
from ml2.ltl import LTLSpecPropertyEncoder
from ml2.data.expr import ExprNotation
from ml2.data.ast import TPEFormat
from ml2.data import vocabulary

In [12]:
vocab = vocabulary.from_iterable(['<p>', 'i0', 'i1', 'o0', 'o1', 'G', 'F', '&', '!', '->', '<s>'])

INFO:root:Constructed vocabulary containing 11 tokens


In [13]:
encoder = LTLSpecPropertyEncoder(property_pad=10, num_properties=7, notation=ExprNotation.INFIX, encoded_notation=ExprNotation.PREFIX, eos=False, tpe_format=TPEFormat.BRANCHDOWN, tpe_pad=8, vocabulary=vocab)

In [14]:
encoder.encode(spec)

True

In [15]:
encoder.tensor

2021-07-30 15:11:33.967686: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


(<tf.Tensor: shape=(7, 10), dtype=int32, numpy=
 array([[10,  5,  1,  0,  0,  0,  0,  0,  0,  0],
        [10,  7,  1,  2,  0,  0,  0,  0,  0,  0],
        [ 5,  8,  7,  3,  4,  0,  0,  0,  0,  0],
        [ 5,  9,  1,  6,  3,  0,  0,  0,  0,  0],
        [ 5,  9,  2,  6,  4,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)>,
 <tf.Tensor: shape=(7, 10, 8), dtype=int32, numpy=
 array([[[0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
       

In [16]:
encoder.error

## LTL Spec Data

In [17]:
import os
from ml2.ltl import LTLSpecData

In [18]:
data = LTLSpecData.load('sc-0')

INFO:ml2.artifact:Found data sc-0 locally
INFO:ml2.ltl.ltl_spec.ltl_spec_data:Successfully constructed dataset of 346 LTL specifications


In [19]:
data.stats()

Computed statistics of 346 specifications
Number of inputs
minimum: 0 maximum: 25 mean: 4.942196531791907 median: 4.0 total: 1710
Number of outputs
minimum: 1 maximum: 37 mean: 3.979768786127168 median: 2.0 total: 1377
Number of assumptions
minimum: 0 maximum: 13 mean: 0.5780346820809249 median: 0.0 total: 200
Number of guarantees
minimum: 1 maximum: 49 mean: 6.658959537572255 median: 4.0 total: 2304
